SELECT COUNT (*) FROM State; 
SELECT COUNT (*) FROM University;
SELECT COUNT (*) FROM Program; 
SELECT COUNT (*) FROM STEM; 
SELECT COUNT (*) FROM Agency;
SELECT COUNT (*) FROM Rank; 
SELECT COUNT (*) FROM ProgramStats; 